-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 14:14:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema com
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `com` ;

-- -----------------------------------------------------
-- Schema com
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `com` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `com` ;

-- -----------------------------------------------------
-- Table `com`.`enum_protocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `com`.`enum_protocol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `com`.`enum_protocol` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_PROTOCOL_NAME` (`name` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `com`.`master_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `com`.`master_site` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `com`.`master_site` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(512) NULL,
  `protocol` INT UNSIGNED NOT NULL,
  `host` VARCHAR(45) NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_SITE` (`protocol` ASC, `host` ASC),
  CONSTRAINT `FK_SITE_PK_PROTOCOL`
    FOREIGN KEY (`protocol`)
    REFERENCES `com`.`enum_protocol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
USE `com` ;

-- -----------------------------------------------------
-- View `com`.`view_site`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `com`.`view_site` ;
SHOW WARNINGS;
USE `com`;
CREATE  OR REPLACE VIEW `view_site` AS
SELECT
	`s`.`id`,
    `p`.`name` AS `protocol`,
    `s`.`host`,
    `s`.`description`,
    `s`.`create_utc`,
    `s`.`update_utc`
FROM
	`master_site` AS `s`
	INNER JOIN `enum_protocol` AS `p`
		ON `s`.`protocol` = `p`.`id`
ORDER BY
	`s`.`id` ASC
;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `com`.`enum_protocol`
-- -----------------------------------------------------
START TRANSACTION;
USE `com`;
INSERT INTO `com`.`enum_protocol` (`id`, `name`, `modify_ts`) VALUES (0, 'HTTP', DEFAULT);
INSERT INTO `com`.`enum_protocol` (`id`, `name`, `modify_ts`) VALUES (1, 'HTTPS', DEFAULT);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
